modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "mysticessentials"
version = "${version}"
displayName = "MysticEssentials"
authors = "Alphine"
description = '''
A EssentialsX Like mod built for customization and ultilty in mind.
'''
#logoFile = ""

[[dependencies.mysticessentials]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mysticessentials]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mysticessentials]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.mysticessentials]]
modId= "luckperms"
type = "required"
versionRange="[5,)"
ordering = "AFTER"
side="SERVER"

[[dependencies.mysticessentials]]
modId="adventure_platform_neoforge"
type = "required"
versionRange="[6.0.0,)" # or whatever you're targeting
ordering="AFTER"
side="BOTH"

[[mixins]]
config = "mysticessentials.mixins.json"
